### ISSUE TITLE
The file organization and pipeline

### ISSUE THREAD

**Issue by Richar-Du** [HLTCHKUST/VG-GPLMs#2]
Thanks for your awesome work! Would you please illustrate how to organize the dataset we download and describe in detail how to run it?

**Comment by TysonYu** [comment]
Hi Richar,
As is shown in the scripts/Bart_text_only.sh or scripts/Bart_multimodal.sh. After downloading the how2 data, you don't need to change the file name and you just need to make sure the files exist in these paths. You can also change the path if you save the How2 data in another place.

        -train_src_path=./dataset/sum_train/tran.tok.txt \
        -train_tgt_path=./dataset/sum_train/desc.tok.txt \
        -val_src_path=./dataset/sum_cv/tran.tok.txt \
        -val_tgt_path=./dataset/sum_cv/desc.tok.txt \
        -test_src_path=./dataset/sum_devtest/tran.tok.txt \
        -test_tgt_path=./dataset/sum_devtest/desc.tok.txt \
        -image_feature_path=./dataset/video_action_features/ \ 

For running, you can directly run the scripts.
