### ISSUE TITLE
about version of transformers

### ISSUE THREAD

**Issue by jyson24** [HLTCHKUST/VG-GPLMs#3]
Hello, 

I tried to run your code and got an error saying that 'force_bos_token_to_be_generated' does not exist in BartConfig.

I think it is because of version of transformers i used.

I used transformers version==4.11.0 and it works well on text-only Bart. The error occurred when I run multimodal task.

Could you let me know the version of transformer you used in your work?

And I want to know the reason why you used './dataset/sum_devtest/tran.tok.txt ' instead of  './dataset/sum_train/tran.tok.txt ' for your 'train_src_path'.

Thank you

**Comment by wenliangdai** [comment]
Hi, as written in the requirements.txt, we use transformers==4.3.2.

For the pathname, there is no specific reason. You can adjust based on your preference, it does not influence the experiment.
