### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by haruhi-sudo** [HLTCHKUST/VG-GPLMs#4]
Hi, thanks for your awesome work! I have a question about the code:
https://github.com/HLTCHKUST/VG-GPLMs/blob/d27a485c3da4869a6a9f2ff902a9c64129b778b1/src/data_preprocess/data_builder.py#L30
Why did you ignore the first word in the src and tgt?
Looking forward to your reply.

**Comment by TysonYu** [comment]
Hi,
Actually, the first word is not a word but the sample ID, which is a number, if you download the date from the way I suggested in the readme.
